[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --config gunicorn.conf.py App:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10