"""Create Ride model

Revision ID: 341b11ae5fc0
Revises: 
Create Date: 2026-04-28 23:36:15.941736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '341b11ae5fc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('driver_lat', sa.Float(), nullable=True),
    sa.Column('driver_lng', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.drop_table('driver_skipped_trips')
    op.drop_table('bookings')
    with op.batch_alter_table('rider_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('rider_details')
    op.drop_table('trip_details')
    with op.batch_alter_table('driver_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('reg_number'))

    op.drop_table('driver_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mobile', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('car_make', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('car_model', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('reg_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('aadhaar_number', mysql.CHAR(length=12), nullable=False),
    sa.Column('licence_validity', sa.DATE(), nullable=True),
    sa.Column('fitness_validity', sa.DATE(), nullable=True),
    sa.Column('pollution_validity', sa.DATE(), nullable=True),
    sa.Column('permit_validity', sa.DATE(), nullable=True),
    sa.Column('account_status', mysql.ENUM('Active', 'Suspended'), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('registered_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('licence_img', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rc_img', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('aadhaar_img', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('permit_img', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('pollution_img', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_photo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('car_color', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('driver_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('reg_number'), ['reg_number'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('trip_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rider_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pickup_location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('drop_location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('distance_km', mysql.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fare', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('ride_date', sa.DATE(), nullable=False),
    sa.Column('ride_time', mysql.TIME(), nullable=False),
    sa.Column('accepted_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('otp', mysql.CHAR(length=4), nullable=True),
    sa.Column('status', mysql.ENUM('Confirmed', 'In Progress', 'Completed', 'Cancelled'), server_default=sa.text("'Confirmed'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('pickup_lat', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('pickup_lon', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('drop_lat', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('drop_lon', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('driver_lat', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('driver_lon', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rider_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mobile', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('account_status', mysql.ENUM('Active', 'Suspended'), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('registered_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rider_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('bookings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pickup_location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('drop_location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('distance', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fare', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ride_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ride_time', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('driver_skipped_trips',
    sa.Column('driver_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('trip_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('driver_name', 'trip_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('rides')
    op.drop_table('users')
    # ### end Alembic commands ###
